title: Scala test 200
category: WIX
sub-Category: Server Guild

tags:
  - Wix
  - Server Onboarding
  - Academy Learning Original

description:
  - content: courses/example-course/01-first-step.md

sections:
  - SectionID: S1
    title: New name
    steps:
      - ID: A1
        title: Step 1 - Setup Scala development environment
        content: courses/example-course/01-first-step.md
        startofstep: courses/example-course/01-first-step.md#abbreviations
        endofstep: courses/example-course/01-first-step.md#custom-containers
      - ID: A2
        title: Step 2 - Clone repository jh
        content: courses/example-course/02-second-step.md
      - ID: A3
        title: Step 3 - Generate Scala Nile project
        content: courses/example-course/03-third-step.md
      - ID: A4
        title: Step 4 - Get your code to master branch
        content: courses/example-course/04-fourth-step.md
      - ID: A5
        title: Step 5 - Get your code to production
        content: courses/example-course/05-fifth-step.md
        startofstep: courses/example-course/05-fifth-step.md#emphasis
        endofstep: courses/example-course/05-fifth-step.md#lists
  - SectionID: S2
    title: New name 2
    steps:
      - ID: A1
        title: Step 1 - Setup Scala development environment
        content: courses/example-course/01-first-step.md
      - ID: A2
        title: Step 2 - Clone repository jh
        content: courses/example-course/02-second-step.md
      - ID: A3
        title: Step 3 - Generate Scala Nile project
        content: courses/example-course/03-third-step.md
      - ID: A4
        title: Step 4 - Get your code to master branch
        content: courses/example-course/04-fourth-step.md
      - ID: A5
        title: Step 5 - Get your code to production
        content: courses/example-course/05-fifth-step.md
  
